### PR TITLE
Feature/gitpod extensions

### PR DESCRIPTION
**Pull request by bennycornelissen**
Added VSCode extensions for Docker (which got automatically installed by Gitpod magic, but is not explicit) and TOML support which is useful when editing the various TOML config files of Hugo

### CODE REVIEW

**Comment by LFSb** [comment]
image
LGTM!

**Review by LFSb — DISMISSED** [review]

**Comment by LFSb** [comment]
@bennycornelissen The failing netlify checks are related to https://github.com/skyworkz/website/pull/71 I'm guessing?

**Comment by bennycornelissen** [comment]
@LFSb no it seems that Netlify somehow can't check out the PR, and I'm struggling to find the option to just re-run the actions without making a new commit. 😞

**Comment by LFSb** [comment]
For later reference: Netlify was asking (very politely) for permissions under the repo integrations. Giving said permissions solved all of our problems.

**Review by LFSb — APPROVED** [review]

**Pull request merged**
